---
- name: Hosts setup for oscap scan
  hosts: all
  gather_facts: true
  strategy: free
  become: true
  vars:
    data_stream_home: "/usr/share/xml/scap/ssg/content/"
  tasks:
    - name: Install necesary packages (Ubuntu16)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libopenscap8
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'

    - name: Install necesary packages (Ubuntu18)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libopenscap8
        - ssg-base
        - ssg-debderived
        - ssg-debian
        - ssg-nondebian
        - ssg-applications
        - openscap-utils
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '18'

    - name: Install necesary packages (Centos)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - openscap-scanner
        - scap-security-guide
      when: ansible_distribution == 'CentOS'

    - name: Copy custom policies
      copy:
        src: files/ds/ssg-{{ ansible_distribution }}{{ ansible_distribution_major_version }}-ds-tailoring.xml
        dest: "{{ data_stream_home }}"

    - name: Copy base policies
      copy:
        src: files/ds/ssg-{{ ansible_distribution }}{{ ansible_distribution_major_version }}-ds.xml
        dest: "{{ data_stream_home }}"
